# Generated by Django 5.0.1 on 2024-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_productcolorimage_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
