# Generated by Django 5.0.1 on 2024-06-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_user_product_price_id_product_stripe_id'),
        ('myapp', '0029_product_price_id_product_stripe_id'),
    ]

    operations = [
    ]
