# Generated by Django 5.0.1 on 2024-06-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_merge_20240610_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_id',
        ),
    ]
