"use client";
import './globals.css';
import { Provider } from 'react-redux';
import { store } from "./redux/store";
import SignUp from "../components/auth/SignUp";
export const metadata = {
  title: 'Zain Wireless',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
    <SignUp/>
      <Provider store={store}>
        <div lang="en">
          {children}
        </div>
      </Provider>
    </>
  );
}
