# Generated by Django 5.0.1 on 2024-07-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorimage',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
