# Generated by Django 5.0.1 on 2024-07-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_color_image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
