# Generated by Django 5.1.6 on 2025-04-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_product_description_productcolorimage_countinstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
